// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXphAg0mBQ84Wv_EKDuS4IfK2Wd1o_dek',
    appId: '1:967599913982:web:788a91d21ef09a246e9eaf',
    messagingSenderId: '967599913982',
    projectId: 'noteapp-9876',
    authDomain: 'noteapp-9876.firebaseapp.com',
    storageBucket: 'noteapp-9876.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvS24TjcqRswIpyIuK4ZZGBnMKK1HVfvk',
    appId: '1:967599913982:android:d18402560e06bcac6e9eaf',
    messagingSenderId: '967599913982',
    projectId: 'noteapp-9876',
    storageBucket: 'noteapp-9876.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuSsK0QIeFAzxDRwT3nFwWrmpqr33MiC4',
    appId: '1:967599913982:ios:5cce336ed5e3e3db6e9eaf',
    messagingSenderId: '967599913982',
    projectId: 'noteapp-9876',
    storageBucket: 'noteapp-9876.appspot.com',
    iosBundleId: 'com.nitha.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuSsK0QIeFAzxDRwT3nFwWrmpqr33MiC4',
    appId: '1:967599913982:ios:5ae41bcd1cf603346e9eaf',
    messagingSenderId: '967599913982',
    projectId: 'noteapp-9876',
    storageBucket: 'noteapp-9876.appspot.com',
    iosBundleId: 'com.nitha.notesapp.RunnerTests',
  );
}
